version: "3.7"

x-env: &env
  NAME: "contracts"
  NETWORK_NAME: "mainnet"

  # Ports
  PORT: "8000"
#  HEALTH_PORT: "8000"
  METRICS_PORT: "9400"

  # Prefix
  REST_PREFIX: "/api/v1"
  HEALTH_PREFIX: "/health"
  METRICS_PREFIX: "/metrics"
  CORS_ALLOW_ORIGINS: "*"

  # Monitoring
  HEALTH_POLLING_INTERVAL: "60"

  # Logging
  LOG_LEVEL: "INFO"
  LOG_TO_FILE: "false"
  LOG_FILE_NAME: "contracts.log"
  LOG_FORMAT: "string"

  # Kafka
  KAFKA_BROKER_URL: "kafka:9092"
  CONSUMER_GROUP: "contracts-consumer-group"
  CONSUMER_TOPIC_BLOCKS: "blocks"

  # DB
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "changeme"
  POSTGRES_SERVER: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "postgres"

  # Endpoints
  MAX_PAGE_SIZE: "100"

  # Application features
  ENABLE_CONTRACT_VERIFICATION: "false"
#  CONTRACTS_S3_AWS_ACCESS_KEY_ID:
#  CONTRACTS_S3_AWS_SECRET_ACCESS_KEY:
#  CONTRACTS_S3_BUCKET:

services:
  contracts-api:
    image: sudoblock/icon-contracts-api:latest
    ports:
      - "8000:8000"
    expose:
      - "9400"
      - "8180"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${CONTRACTS_CONTEXT:-.}/icon_contracts:/app
    environment:
      <<: *env

  contracts-worker:
    image: sudoblock/icon-contracts-worker:latest
    ports:
      - "8181:8181"     # Health
      - "9401:9401"     # Prometheus
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    environment:
      <<: *env
